# Write your MySQL query statement below
SELECT CUSTOMER_ID, COUNT(customer_id) AS count_no_trans
FROM VISITS LEFT JOIN TRANSACTIONS
ON VISITS.VISIT_ID = TRANSACTIONS.VISIT_ID
WHERE TRANSACTION_ID IS NULL
GROUP BY CUSTOMER_ID;
